version: '3'  # Docker Compose 파일의 버전을 지정
services:  # 실행할 서비스 목록을 정의
  db:
    image: mongo:latest
    container_name: mace_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: betterthendesmos
    volumes:
      - ./db:/data/db
      
  back:
    build: ./back
    container_name: mace_back
    depends_on:
      - db
    environment:
      - MONGO_DB_URL=mongodb://root:betterthendesmos@db:27017
    volumes:
      - ./back:/app
    tty: true
    stdin_open: true

  front:
    image: node:18 # Node.js 버전
    working_dir: /app
    volumes:
      - ./front:/app
    command:
      - sh
      - -c
      - |
        yarn install
        yarn start

  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80' # 포트 매핑
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf # Nginx 설정 파일을 로컬 디렉토리와 공유
      # - ./front/build:/usr/share/nginx/html
    depends_on:
      - back
      - front